# Generated by Django 4.1.4 on 2023-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('datetime_send', models.DateTimeField(blank=True, null=True)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat',
                'ordering': ['datetime_send'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='appChat',
        ),
    ]
