# Generated by Django 4.1.1 on 2023-02-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsettings',
            options={'managed': False},
        ),
    ]
