# Generated by Django 4.1.4 on 2023-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_mailsettings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
