# Generated by Django 4.1.4 on 2023-08-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_categorychoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='categorychoice',
            options={'managed': False, 'verbose_name': 'Выбранные категории'},
        ),
        migrations.AlterModelOptions(
            name='thema',
            options={'managed': True, 'verbose_name': 'Категории работ'},
        ),
        migrations.AlterField(
            model_name='category',
            name='ordernumber',
            field=models.ForeignKey(db_column='orderNumber', on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_order_number', to='applications.email'),
        ),
    ]
