# Generated by Django 4.1.4 on 2023-08-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_email_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'managed': False, 'ordering': ['-datetime_send'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
