# Generated by Django 4.1.4 on 2023-08-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_email_category_email_specialist_email_uid_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='category',
        ),
    ]
