# Generated by Django 4.1.4 on 2023-08-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_remove_email_category_email_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_chat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
