# Generated by Django 4.1.4 on 2023-08-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_email_is_chat_email_specialist_email_uid_division_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': True, 'ordering': ['datetime_send']},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'managed': False, 'ordering': ['-datetime_send'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
