# Generated by Django 4.1.4 on 2023-08-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_chat_options_alter_email_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.email'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='datetime_send',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender_id',
            field=models.IntegerField(blank=True, db_column='sender_id', null=True),
        ),
    ]
