# Generated by Django 4.1.4 on 2023-08-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_alter_chat_chat_id_alter_chat_datetime_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.ForeignKey(blank=True, db_column='chat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.email'),
        ),
    ]
