# Generated by Django 4.1.4 on 2023-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_chat_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': True, 'ordering': ['-datetime_send']},
        ),
        migrations.AlterField(
            model_name='thema',
            name='name',
            field=models.CharField(choices=[('Prnt', 'Оргтехника'), ('Srv', 'Сервера'), ('Soft', 'Программное обеспечение'), ('Help', 'Помощь пользователям'), ('Vdo', 'Видеонаблюдение'), ('1c', '1c'), ('lan', 'Монтаж лвс')], max_length=5, unique=True),
        ),
    ]
