# Generated by Django 4.1.4 on 2023-08-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_email_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_order', to='applications.orderauthor'),
        ),

    ]
