# Generated by Django 4.1.4 on 2023-07-31 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_datetime_add',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 31, 16, 2, 55, 519091), null=True),
        ),
    ]
