# Generated by Django 4.1.4 on 2023-07-31 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_todo_todo_datetime_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_datetime_add',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
