# Generated by Django 4.1.4 on 2023-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todo_todo_datetime_add'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': True, 'ordering': ['-todo_datetime_add']},
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_datetime_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
