# Generated by Django 4.1.4 on 2023-08-28 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0004_alter_todo_options_alter_todo_todo_datetime_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
